CREATE TABLE Cars
( Car_ID INT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  User_ID VARCHAR(20) NOT NULL,
  CarMake VARCHAR(10) NOT NULL,
  CarModel VARCHAR(10) NOT NULL,
  CarYear VARCHAR(10) NOT NULL,
  LicencePlate VARCHAR(20) NOT NULL,
  CarImage VARCHAR(10),
  FOREIGN KEY (User_ID) REFERENCES Users (User_ID)
);

CREATE TABLE Users 
( User_ID VARCHAR(20) NOT NULL PRIMARY KEY,
  Fname VARCHAR(20) NOT NULL,
  Lname VARCHAR(20) NOT NULL,
  Email VARCHAR(40) NOT NULL,
  Password VARCHAR(270) NOT NULL,
  Zest VARCHAR(15) NOT NULL,
  Authority INT(4) NOT NULL
);

CREATE TABLE u_Access
( Access_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  User_ID VARCHAR(20) NOT NULL,
  Acc_op INT(1) NOT NULL,
  FOREIGN KEY (User_ID) REFERENCES Users (User_ID)
);

CREATE TABLE Logs
( Log_ID INT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Log_TS TIMESTAMP,
  User_ID VARCHAR(20) NOT NULL,
  Car_ID INT UNSIGNED NOT NULL,
  FOREIGN KEY (User_ID) REFERENCES Users (User_ID),
  FOREIGN KEY (Car_ID) REFERENCES Cars (Car_ID)
);